title: PrivateUnsecuredLoanApplicationCreated
description: |
  An event indicating the creation of an application for
  a private unsecured loan.
type: object
additionalProperties: false
'$id': 'https://open-broker.org/schema/v0/no/PrivateUnsecuredLoanApplicationCreated'
'$schema': 'http://json-schema.org/draft-06/schema#'
definitions:
  extensionPoint:
    title: Extension data
    additionalProperties: false
    patternProperties:
      '^(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9-][a-zA-Z0-9]).)([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9-]*[A-Za-z0-9])$':
        type: object
  application:
    type: object
    additionalProperties: false
    required:
      - loanAmount
      - termMonths
      - applicant
      - loanPurpose
    properties:
      loanAmount:
        type: integer
        title: Amount to borrow
        description: The amount that the customer wishes to borrow
        minimum: 1
        examples:
          - 50000
      termMonths:
        type: integer
        title: Number of monthly terms
        description: The number of 1-month terms that the applicant desires to pay off the loan over
        minimum: 1
        examples:
          - 24
      refinanceAmount:
        type: integer
        title: The amount being refinanced
        description: Must be less than or equal to the loanAmount
        examples:
          - 25000
      extensions:
        '$ref': '#/definitions/extensionPoint'
        '$linkVal': extensionPoint
        title: Custom, vendor-specific extensions to the schema
      applicant:
        '$ref': '#/definitions/applicant'
        '$linkVal': applicant
        title: Applicant
        description: The primary applicant to the loan
      coApplicant:
        '$ref': '#/definitions/applicant'
        '$linkVal': applicant
        title: Co-applicant
        description: A secondary applicant for the loan, if any.
      existingLoans:
        type: array
        title: Information about existing loans relevant to the applicant
        items:
          '$ref': '#/definitions/existingLoan'
          '$linkVal': existingLoan
      loanPurpose:
        type: string
        title: Purpose of the loan
        description: Categorical label for the purpose of the loan being applied for
        default: OTHER
        'meta:enum':
          REFINANCE: Refinancing existing debt
          HOME_REMODELLING: Home remodelling or renovation
          HEALTHCARE_EXPENSES: To finance health-care costs.
          INVESTMENT: To finance an investment
          EDUCATION: To finance education of some kind
          TRAVEL: To finance a vacation or other travel expenses
          CAR: To finance the purchase of a car or similar
          OTHER: Purpose not fitting the above categories
        enum:
          - REFINANCE
          - HOME_REMODELLING
          - HEALTHCARE_EXPENSES
          - INVESTMENT
          - EDUCATION
          - TRAVEL
          - CAR
          - OTHER
  existingLoan:
    type: object
    required:
      - loanAmount
      - monthlyPayment
      - existingLoanType
      - responsibility
      - lender
    properties:
      loanAmount:
        type: integer
        minimum: 1
      monthlyPayment:
        type: integer
        minimum: 1
      refinanceAmount:
        type: integer
        minimum: 0
      existingLoanType:
        type: string
        'meta:enum':
          CAR_LOAN: A loan for a car or similar vehicle
          CREDIT_CARD: A credit-card
          MORTGAGE: A home mortgage
          STUDENT_LOAN: A student loan
          UNSECURED_LOAN: An unsecured loan, not falling into any of the other categories, for example a consumer loan.
          OTHER: Any other debt not falling into any of the other categories.
        enum:
          - CAR_LOAN
          - CREDIT_CARD
          - MORTGAGE
          - STUDENT_LOAN
          - UNSECURED_LOAN
          - OTHER
      responsibility:
        type: string
        'meta:enum':
          MAIN_APPLICANT: The main applicant is responsible for this loan
          CO_APPLICANT: The co-applicant is responsible for this loan
          SHARED: The loan is a shared responsibility for the applicants
        enum:
          - MAIN_APPLICANT
          - CO_APPLICANT
          - SHARED
      lender:
        type: string
        minLength: 1
  countryCode:
    type: string
    minLength: 2
    maxLength: 2
    pattern: '[A-Z]{2}'
  countryCodeArray:
    type: array
    uniqueItems: true
    items:
      '$ref': '#/definitions/countryCode'
      '$linkVal': countryCode
  address:
    type: object
    additionalProperties: false
    required:
      - firstName
      - lastName
      - address
      - city
      - postalCode
    properties:
      firstName:
        type: string
        minLength: 1
      lastName:
        type: string
        minLength: 1
      address:
        type: string
        minLength: 1
      city:
        type: string
        minLength: 1
      postalCode:
        type: string
        minLength: 1
      careOf:
        type: string
        minLength: 1
  applicant:
    additionalProperties: false
    type: object
    required:
      - ssn
      - employmentStatus
      - employmentStatusSinceYear
      - employmentStatusSinceMonth
      - dependentChildren
      - housingType
      - housingCostPerMonth
      - netMonthlyIncome
      - maritalStatus
      - citizenships
      - countriesOfResidence
      - taxResidentOf
    properties:
      ssn:
        type: string
        title: 11-digit Social Security Number (no. Fodselsnummer)
        description: A Norweigian Social Security number in 11-digit format DDMMYYXXXXX
        pattern: '^[0-9]{11}$'
        minLength: 11
        maxLength: 11
        examples:
        - '31128012345'
      phone:
        type: string
        title: Phone number to the applicant
        pattern: '^\+[1-9][0-9]{1,14}$'
        examples:
        - '+4740123456'
      secondaryPhone:
        title: List of alternate phone numbers
        type: array
        items:
          type: string
          pattern: '^\+[1-9][0-9]{1,14}$'
      emailAddress:
        type: string
        format: email
        title: Email address to the applicant
      employmentStatus:
        type: string
        title: The employment situation of the applicant
        'meta:enum':
          DOMESTIC: Managing the home without employment
          EARLY_RETIRED: Retired earlier before the usual retirement age (no. Ufor)
          HOURLY: Formally permanently employed, hired by the hour
          OTHER: An employment status not falling neatly in to any of the other categories
          PRIVATE_SECTOR: Employed full-time in the private sector
          PUBLIC_SECTOR: Employed full-time in the public sector
          REHABILITATION: Temporarily receiving financial support due to injury or disease (no. AAP)
          RETIRED: Retired due to age
          SELF_EMPLOYED: The applicant is a sole proprietor or works for his or her own company
          STUDENT: Signed up to a university or other higher education
          TEMPORARY: Employment pertaining to a limited time period (no. Midlertidig ansatt)
          TEMPORARILY_DISCHARGED: Employed, but temporarily not working (no. permittering)
          TRIAL: Trial employment (no. Proveansatt)
          UNEMPLOYED: Not currently employed
        enum:
          - DOMESTIC
          - EARLY_RETIRED
          - HOURLY
          - OTHER
          - PRIVATE_SECTOR
          - PUBLIC_SECTOR
          - REHABILITATION
          - RETIRED
          - SELF_EMPLOYED
          - STUDENT
          - TEMPORARY
          - TEMPORARILY_DISCHARGED
          - TRIAL
          - UNEMPLOYED
      employmentStatusSinceYear:
        type: integer
        title: Year in which the applicant entered into his or her current employment status
        minimum: 1900
        maximum: 3000
        examples:
        - 2010
      employmentStatusSinceMonth:
        type: integer
        title: Month in which the applicant entered into his or her current employment status
        minimum: 1
        maximum: 12
        examples:
        - 12
      employmentStatusUntilYear:
        type: integer
        title: Year in which the applicant ended his or her current employment status (for temporary employment)
        minimum: 1900
        maximum: 3000
        examples:
        - 2010
      employmentStatusUntilMonth:
        type: integer
        title: Month in which the applicant ended his or her current employment status (for temporary employment)
        minimum: 1
        maximum: 12
        examples:
        - 12
      employerName:
        type: string
        title: The company name of the employer
        examples:
        - Example AB
      employerPhone:
        type: string
        pattern: '^\+[1-9][0-9]{1,14}$'
        examples:
        - '+4740123456'
      dependentChildren:
        type: integer
        title: Number of dependent children
        description: |
          Number of child dependents under the age of 18.
          If greater than 15, then 15 is sent.
        default: 0
        minimum: 0
        maximum: 15
      childSupportReceivedMonthly:
        type: integer
        minimum: 0
        title: Money received for child-support each month
      rentReceivedMonthly:
        type: integer
        minimum: 0
        title: Money received for rent each month
      otherIncomeReceivedMonthly:
        type: integer
        minimum: 0
        title: Money received each month for categories outside child-support and rent
      childSupportPaidMonthly:
        type: integer
        minimum: 0
        title: Money paid for child-support each month
      paymentRemark:
        type: boolean
        title: Payment remark
        description: |
          Indicate whether an applicant has a payment remark or not, due to a failure to
          pay an outstanding bill.
      housingType:
        type: string
        title: Applicant's housing type
        description: The form of housing in which the applicant resides
        'meta:enum':
          COOPERATIVE: The applicant owns a part in a housing cooperative (no. Borettslag)
          LODGER: The applicant rents accomodation in another's house (no. Leieboer)
          OTHER: A housing situation not falling neatly in to any of the other categories
          OWN_APARTMENT: The applicant owns his or her apartment (no. Selveier)
          OWN_HOUSE: The applicant owns his or her house (no. Eier)
          PARENTS: The applicant is living with his or her parents
          RENTED: The applicant rents his or her place of residence (no. Leier)
        enum:
          - COOPERATIVE
          - LODGER
          - OTHER
          - OWN_APARTMENT
          - OWN_HOUSE
          - PARENTS
          - RENTED
      housingSinceYear:
        type: integer
        minimum: 1900
        maximum: 3000
        title: Year in which the applicant entered into his or her current housing
        examples:
        - 2010
      housingSinceMonth:
        type: integer
        title: Month in which the applicant entered into his or her current housing
        minimum: 1
        maximum: 12
        examples:
        - 12
      housingCostPerMonth:
        type: integer
        title: Housing-related costs per month
        default: 0
        minimum: 0
        examples:
        - 10000
      netMonthlyIncome:
        type: integer
        minimum: 0
        title: The monthly net (post-tax) income of the applicant
      grossYearlyIncome:
        type: integer
        minimum: 0
        title: The yearly gross (pre-tax) income of the applicant
      partnerYearlyIncome:
        type: integer
        minimum: 0
        title: The yearly gross (pre-tax) income of the applicant's partner
      maritalStatus:
        type: string
        title: The marital status of the applicant
        'meta:enum':
          COHABITING: no. Samboer
          DIVORCED: no. Skilt
          MARRIED: no. Gift or Partnerskap
          SINGLE: no. Ugift
          WIDOW_OR_WIDOWER: no. Enke
        enum:
          - COHABITING
          - DIVORCED
          - MARRIED
          - SINGLE
          - WIDOW_OR_WIDOWER
      bankAccount:
        type: string
        title: Applicant's bank account number
        pattern: '^[0-9]{11}$'
        minLength: 11
        maxLength: 11
      citizenships:
        title: Countries that the applicant is a citizen of
        '$ref': '#/definitions/countryCodeArray'
        '$linkVal': countryCodeArray
      livedInCountrySinceYear:
        type: integer
        minimum: 1900
        maximum: 3000
        title: Year in which the applicant started living in the country
        examples:
        - 2010
      countriesOfResidence:
        title: Countries that the applicant is a resident of
        '$ref': '#/definitions/countryCodeArray'
        '$linkVal': countryCodeArray
      taxResidentOf:
        title: Countries that the applicant is a tax resident of
        '$ref': '#/definitions/countryCodeArray'
        '$linkVal': countryCodeArray
      education:
        type: string
        title: The highest education level of the applicant
        'meta:enum':
          PRIMARY_SCHOOL: Completed the obligatory first stage of formal education (no. Grunnskole)
          SECONDARY_SCHOOL: Completed the formal education preparing for higher studies (no. Gymnasium)
          UNIVERSITY_SHORT: Completed 1-3 years of higher education
          UNIVERSITY_LONG: Completed 4 or more years of higher education
        enum:
          - PRIMARY_SCHOOL
          - SECONDARY_SCHOOL
          - UNIVERSITY_SHORT
          - UNIVERSITY_LONG
      tentativeAddress:
        title: Address of the applicant
        description: |
          All actors are expected to perform proper due diligence in
          establishing the identity of the applicant
        '$ref': '#/definitions/address'
        '$linkVal': address
required:
  - brokerReference
  - dataProtectionContext
  - application
properties:
  brokerReference:
    title: A reference-id used by the broker
    '$ref': 'https://open-broker.org/schema/v0/no/reference'
  dataProtectionContext:
    type: string
    title: The data-protection context of the application
    description: |
      Consumers MAY reject or refuse to process data sent in the REAL
      data protection context if the consumer deems it cannot secure
      the data being sent. Additionally consumers may reject FICTIONAL
      data if processing may affect real persons, for example,
      ordering a hard credit inquiry.
    'meta:enum':
      REAL: Production data concerning real data-subjects
      FICTIONAL: Fictional data, does not concern real data-subjects
    enum:
      - REAL
      - FICTIONAL
  application:
    '$ref': '#/definitions/application'
